apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: uppound-aws
spec:
  dependsOn:
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: '>=v0.0.0'
  - configuration: xpkg.upbound.io/upbound/configuration-aws-eks
    version: '>=v0.0.0'
  - configuration: xpkg.upbound.io/upbound/configuration-aws-network
    version: v0.23.0
  - provider: xpkg.upbound.io/upbound/provider-kubernetes
    version: v0.16.0
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/acmeco/uppound-aws
  source: github.com/upbound/project-template
