apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapps.python.app.uppound.io
  labels:
    language: python
spec:
  compositeTypeRef:
    apiVersion: app.uppound.io/v1alpha1
    kind: XApp
  mode: Pipeline
  pipeline:
  - functionRef:
      name: acmeco-uppounduppound-function-python
    step: uppound-function
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
